name: DanceAlarm
options:
  bundleIdPrefix: com.sh1zoooo
  deploymentTarget:
    iOS: "16.0"
targets:
  DanceAlarm:
    type: application
    platform: iOS
    sources:
      - path: DanceAlarm
    info:
      path: DanceAlarm/Info.plist
      properties:
        UILaunchScreen: {}
        CFBundleDisplayName: "Разбудильник"
        NSCameraUsageDescription: "Камера нужна, чтобы выполнить задание для выключения будильника (например, отследить танец, сканировать QR-код или показать унитаз)"
        NSMotionUsageDescription: "Датчики движения нужны, чтобы отследить танец или тряску телефона для выключения будильника"
        UIBackgroundModes:
          - audio
        UIRequiredDeviceCapabilities:
          - armv7
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sh1zoooo.dancealarm
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
